# A simple action usage
name: Build Kernel Redmi 10X4G
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Kernel Redmi 10X4G
        uses: oyzc0227-boop/kernel_build_action@main
        with:
          kernel-url: https://github.com/LineageOS/android_kernel_xiaomi_mt6768.git
          kernel-branch: lineage-20.0
          config: merlin_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          ksu-version: v4.1.2
          ksu-other: true
          ksu-url: https://github.com/SukiSU-Ultra/SukiSU-Ultra
          android-version: 12
          aosp-clang-version: r383902
          disable-lto: true
          anykernel3: true
